services:
  gost:
    image: gogost/gost:latest
    container_name: tyz-gost
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./gost.json:/etc/gost/gost.json

  app:
    image: ghcr.io/laoshan-tech/tyz-node:latest
    container_name: tyz-app
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./.env:/app/.env